homework for meal sharing app react2 week2
aladdin91/meal-sharing pull request #6
Opened 2023-03-27 23:04 UTC by aladdin91

this is my h/w for meal sharing app react2 week2

2023-04-11 15:45 UTC, shpomp requested changes
Overall quite a good job! 👏🏽 
There are some not-so-weel organised parts though that makes it difficult to read and understand the code and the app structure 🙏🏽

2023-04-11 15:45 UTC, shpomp commented on src/client/components/ReservationForm.jsx
> +        {/* i have to incloud id because the database does not increse the
👀

2023-04-11 15:45 UTC, shpomp commented on src/client/components/MealList.jsx
> +      <Footer />
The whole content of this file is a bit of a mess. Please clean it up 🙏🏽

2023-04-11 15:45 UTC, shpomp commented on src/client/components/MealDetail.jsx
> +  const meal = meals.find((meal) => meal.id === Number(id));
Such a component that is meant to display details of a single meal - if I understood correctly - should definitely have a single meal passed into it as props.
Why would it need to know about all the meals and filter them? 🤔

2023-04-11 15:45 UTC, shpomp commented on src/client/components/Meal.jsx
> +function Meal({ meal }) {
Why do we have this and also the MealDetail?

2023-04-11 15:45 UTC, shpomp commented on src/backend/api/reviews.js
> +    res.status(500).send(err)
Are you sure that 500 is the right status here? 🤓

2023-04-12 21:56 UTC, aladdin91 commented
thanks a lot Karo for the review 🙏, i fixed it according to the review in the finel homework

2023-04-12 21:56 UTC, merged