homework for meal sharing app react2 week3
aladdin91/meal-sharing pull request #7
Opened 2023-04-05 15:11 UTC by aladdin91

this is my meal sharing app react2 week3 homework

2023-04-11 15:57 UTC, shpomp requested changes
Looks good, a lot of good work done! 💪🏽 
I left some questions to challenge the parts that caught my eye, I hope you can brush it up and refactor a bit to make it cleaner and ensure particular functionalities. 🙏🏽 
Make sure to take care of the routes for a single meal and for the reviews (wether it would be a separate rout or an inclusion into meal details). 🤞🏽

2023-04-11 15:57 UTC, shpomp commented on src/backend/api/meals.js
> +router.get('/meals/details', async (req, res) => {
This route does not indicate any specific meal, so it is essentially incorrect. 
Neither in the query -  you do not have the meal id that you would use to fetch the details. 
By all means this looks like it would not be working. Try to refactor so you have the right path, params and all 🙏🏽

2023-04-11 15:57 UTC, shpomp commented on src/backend/api/reviews.js
> +  try {
This very much looks like a path that fetches one meal by the id. 
How would I know that this path is for reviews?

2023-04-11 15:57 UTC, shpomp commented on src/client/components/MealList.jsx
> +    const sortFunction = (a, b) => {
Could the sorting function be extracted into a separate one that takes the sorting parameters? 💡

2023-04-11 15:57 UTC, shpomp commented on src/client/components/SearchMeals.jsx
> +  const [searchMeals, setSearchMeals] = useState([]);
Why is the initial state not the meals that you get from the context?

2023-04-12 22:07 UTC, aladdin91 commented
thanks a lot Karo for the review, this was realy informative 🙏

2023-04-12 22:07 UTC, merged